# Generated by Django 5.2.3 on 2025-07-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_material_submitted_by_alter_material_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='employee_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
