# Generated by Django 5.2.3 on 2025-07-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_payroll_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='employee_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
