# Generated by Django 5.2 on 2025-07-23 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_attendance_check_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.CharField(max_length=100)),
                ('hours', models.FloatField()),
                ('work_description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
